# Generated by Django 3.2.5 on 2021-07-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
